"""initial schema

Revision ID: 1a872dedc99f
Revises: 
Create Date: 2026-10-05 08:02:52.858822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a872dedc99f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=64), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_setting_key'), ['setting_key'], unique=True)

    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_code', sa.String(length=12), nullable=False),
    sa.Column('host_token_hash', sa.String(length=255), nullable=False),
    sa.Column('host_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_sessions_session_code'), ['session_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_game_sessions_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('normalized_word', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('part_of_speech', sa.String(length=32), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('frequency_score', sa.Float(), nullable=False),
    sa.Column('is_proper_noun', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_word', 'language', name='uq_word_lang')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_frequency_score'), ['frequency_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_normalized_word'), ['normalized_word'], unique=False)

    op.create_table('session_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('player_token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'display_name', name='uq_player_name_session')
    )
    with op.batch_alter_table('session_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_players_session_id'), ['session_id'], unique=False)

    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('captain_player_id', sa.Integer(), nullable=True),
    sa.Column('current_team', sa.String(length=8), nullable=False),
    sa.Column('board_size', sa.Integer(), nullable=False),
    sa.Column('word_mode', sa.String(length=16), nullable=False),
    sa.Column('timer_duration', sa.Integer(), nullable=False),
    sa.Column('timer_started_at', sa.DateTime(), nullable=True),
    sa.Column('timer_paused_at', sa.DateTime(), nullable=True),
    sa.Column('red_score', sa.Integer(), nullable=False),
    sa.Column('blue_score', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['captain_player_id'], ['session_players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rounds_status'), ['status'], unique=False)

    op.create_table('round_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('card_type', sa.String(length=16), nullable=False),
    sa.Column('is_revealed', sa.Boolean(), nullable=False),
    sa.Column('revealed_at', sa.DateTime(), nullable=True),
    sa.Column('revealed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['revealed_by'], ['session_players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'position', name='uq_card_position')
    )
    with op.batch_alter_table('round_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_cards_round_id'), ['round_id'], unique=False)

    op.create_table('round_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['session_players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'player_id', name='uq_round_player')
    )
    with op.batch_alter_table('round_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_players_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_players_round_id'), ['round_id'], unique=False)

    op.create_table('session_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['session_players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_session_id'), ['session_id'], unique=False)

    op.create_table('guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('normalized_word', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['round_cards.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['session_players.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['session_players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guesses_normalized_word'), ['normalized_word'], unique=False)
        batch_op.create_index(batch_op.f('ix_guesses_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guesses_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guesses_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guesses_status'))
        batch_op.drop_index(batch_op.f('ix_guesses_round_id'))
        batch_op.drop_index(batch_op.f('ix_guesses_player_id'))
        batch_op.drop_index(batch_op.f('ix_guesses_normalized_word'))

    op.drop_table('guesses')
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_events_round_id'))
        batch_op.drop_index(batch_op.f('ix_session_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_session_events_created_at'))

    op.drop_table('session_events')
    with op.batch_alter_table('round_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_players_round_id'))
        batch_op.drop_index(batch_op.f('ix_round_players_player_id'))

    op.drop_table('round_players')
    with op.batch_alter_table('round_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_cards_round_id'))

    op.drop_table('round_cards')
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_status'))
        batch_op.drop_index(batch_op.f('ix_rounds_session_id'))

    op.drop_table('rounds')
    with op.batch_alter_table('session_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_players_session_id'))

    op.drop_table('session_players')
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_normalized_word'))
        batch_op.drop_index(batch_op.f('ix_words_is_active'))
        batch_op.drop_index(batch_op.f('ix_words_frequency_score'))
        batch_op.drop_index(batch_op.f('ix_words_difficulty'))
        batch_op.drop_index(batch_op.f('ix_words_category'))

    op.drop_table('words')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_game_sessions_session_code'))

    op.drop_table('game_sessions')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_setting_key'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
