"""vocabulary engine schema

Revision ID: 26918270eaa9
Revises: 1a872dedc99f
Create Date: 2026-10-05 08:33:57.597441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26918270eaa9'
down_revision = '1a872dedc99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('dataset_url', sa.String(length=512), nullable=True),
    sa.Column('resume_offset', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_processed', sa.BigInteger(), nullable=False),
    sa.Column('total_imported', sa.BigInteger(), nullable=False),
    sa.Column('total_updated', sa.BigInteger(), nullable=False),
    sa.Column('total_duplicates', sa.BigInteger(), nullable=False),
    sa.Column('total_rejected', sa.BigInteger(), nullable=False),
    sa.Column('total_errors', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_imports_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_imports_status'), ['status'], unique=False)

    op.create_table('vocabulary_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('license_name', sa.String(length=128), nullable=True),
    sa.Column('license_url', sa.String(length=512), nullable=True),
    sa.Column('homepage_url', sa.String(length=512), nullable=True),
    sa.Column('dataset_url', sa.String(length=512), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('word_count', sa.BigInteger(), nullable=False),
    sa.Column('last_imported_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_sources_name'), ['name'], unique=True)

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_multiword', sa.Boolean(), nullable=False,
                                      server_default='0'))
        batch_op.add_column(sa.Column('character_count', sa.Integer(), nullable=False,
                                      server_default='0'))
        batch_op.add_column(sa.Column('source_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False,
                                      server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.alter_column('word',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('normalized_word',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_words_is_multiword'), ['is_multiword'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_is_proper_noun'), ['is_proper_noun'], unique=False)
        batch_op.create_index('ix_words_lang_active_cat', ['language', 'is_active', 'category'], unique=False)
        batch_op.create_index('ix_words_lang_active_diff', ['language', 'is_active', 'difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_source'), ['source'], unique=False)

    # Backfill derived columns for rows that already existed before this
    # migration so pre-existing vocabulary stays consistent.
    op.execute(
        "UPDATE words SET character_count = CHAR_LENGTH(word) "
        "WHERE character_count = 0"
    )
    op.execute(
        "UPDATE words SET is_multiword = 1 WHERE word LIKE '% %'"
    )
    op.execute(
        "UPDATE words SET updated_at = created_at "
        "WHERE updated_at > created_at"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_source'))
        batch_op.drop_index(batch_op.f('ix_words_language'))
        batch_op.drop_index('ix_words_lang_active_diff')
        batch_op.drop_index('ix_words_lang_active_cat')
        batch_op.drop_index(batch_op.f('ix_words_is_proper_noun'))
        batch_op.drop_index(batch_op.f('ix_words_is_multiword'))
        batch_op.alter_column('normalized_word',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('word',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('source_id')
        batch_op.drop_column('character_count')
        batch_op.drop_column('is_multiword')

    with op.batch_alter_table('vocabulary_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_sources_name'))

    op.drop_table('vocabulary_sources')
    with op.batch_alter_table('vocabulary_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_imports_status'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_imports_source'))

    op.drop_table('vocabulary_imports')
    # ### end Alembic commands ###
